name: 'Install CMake'
inputs:
  version:
    description: 'CMake version in the form 3.18.4 or 3.19.0-rc2 for RCs'
    required: false
runs:
  using: "composite"
  steps:
    - name: Install CMake
      run: |
        pip3 install BeautifulSoup4 requests
        if [ "$RUNNER_OS" == "Windows" ]; then python_cmd=python; else python_cmd=python3; fi
        if [ ! -z "${{ inputs.version }}" ]; then python_cmd_input="--version ${{ inputs.version }}"; fi
        echo
        echo $python_cmd_input
        $python_cmd $GITHUB_ACTION_PATH/install_cmake.py $python_cmd_input
      shell: bash
