name: 'Install CMake'
inputs:
  version:
    description: 'CMake version in the form of 3.24.3 or 3.25.0-rc4 for release candidates'
    required: false
  release-candidate:
    description: 'Consider a release candidate when selecting the latest version'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: pip3 install -r requirements.txt
      shell: bash

    - name: Install CMake
      run: |
        if [ ! -z "${{ inputs.version }}" ]; then
            input_version=--version ${{ inputs.version }}
        fi
        if [ "${{ inputs.release-candidate }}" = true ]; then
            input_rc=--rc
        fi
        echo
        python3 $GITHUB_ACTION_PATH/install_cmake.py $input_version $input_rc
      shell: bash
