name: 'Install Latest CMake'
description: 'Install CMake so you can use the latest release, latest release candidate, or a specific version'
inputs:
  version:
    description: 'CMake version in the form of 3.24.3 or 3.25.0-rc4 for release candidates'
    required: false
  release-candidate:
    description: 'Consider a release candidate when selecting the latest version'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Setup Python venv and install deps
      shell: bash
      run: |
        # Create a temporary virtual environment to avoid PEP 668 restrictions
        python3 -m venv "$RUNNER_TEMP/instcmake_venv"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          echo "$RUNNER_TEMP/instcmake_venv/Scripts" >> "$GITHUB_PATH"
        else
          echo "$RUNNER_TEMP/instcmake_venv/bin" >> "$GITHUB_PATH"
        fi
        # Upgrade pip inside the venv and install requirements
        python -m pip install --upgrade pip
        python -m pip install -r "$GITHUB_ACTION_PATH/requirements.txt"

    - name: Install CMake
      run: |
        if [ ! -z "${{ inputs.version }}" ]; then
            input_version="--version ${{ inputs.version }}"
        fi
        if [ "${{ inputs.release-candidate }}" = true ]; then
            input_rc="--rc"
        fi
        echo
        python "$GITHUB_ACTION_PATH/install_cmake.py" $input_version $input_rc
      shell: bash
